### ISSUE TITLE
CenMap running stopped at installing pip dependencies step (ModDotPlot)

### ISSUE THREAD

**Issue by chunlinxiao** [logsdon-lab/CenMAP#74]
Hi,

I was testing cenmap, but it stopped at below.  I also tried to install ModDotPlot myself, and it seemed to fail here. Taking suggestion from others to install PIL  by using "pip install Pillow", I verified that PIL was installed lib/python3.11/site-packages/PIL, but re-run cen-map or re-installing ModDotPlot still failed at the same step.  Do you have any suggestion?  thanks

Installing pip dependencies: ...working... Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/marbl/ModDotPlot.git /tmp/pip-req-build-a2z6p7l1
ERROR: Ignored the following versions that require a different python version: 1.10.0 Requires-Python <3.12,>=3.8; 1.10.0rc1 Requires-Python <3.12,>=3.8; 1.10.0rc2 Requires-Python <3.12,>=3.8; 1.10.1 Requires-Python <3.12,>=3.8; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 1.9.0 Requires-Python >=3.8,<3.12; 1.9.0rc1 Requires-Python >=3.8,<3.12; 1.9.0rc2 Requires-Python >=3.8,<3.12; 1.9.0rc3 Requires-Python >=3.8,<3.12; 1.9.1 Requires-Python >=3.8,<3.12
ERROR: Could not find a version that satisfies the requirement PIL (from moddotplot) (from versions: none)
ERROR: No matching distribution found for PIL

failed

CondaEnvException: Pip failed

**Comment by koisland** [comment]
Hi chunlinxiao,

I believe PR #73 fixes this issue. Can you try `git pull` to get the most recent pipeline version?

**Comment by chunlinxiao** [comment]
Hi @koisland thanks for the suggestion for reducing num of threads, indeed, it helped get the cenmap going until the following error - appreciate if you could provide some suggestion.  Many thanks.


Activating conda environment: .snakemake/conda/d929071de8a7c5c417717672309902e4_
Touching output file results/humas_hmmer/split_cens_for_humas_hmmer_chr21.done.
[Wed Sep 18 14:47:46 2024]
Finished job 365.
321 of 562 steps (57%) done
MissingInputException in rule get_live_hor in file CenMAP/workflow/rules/plot_hor_stv.smk, line 5:
Missing input files for rule get_live_hor:
    output: results/hor_stv/bed/chr21/HG002_chr21_chr21_MATERNAL:12248025-14043023_renamed.bed, results/hor_stv/bed/chr21/HG002_chr21_chr21_MATERNAL:12248025-14043023_liveHORs.bed
    wildcards: chr=chr21, fname=HG002_chr21_chr21_MATERNAL:12248025-14043023
    affected files:
        workflow/scripts/stv_fix/scripts/live_HORs_filter.py

**Comment by koisland** [comment]
Ah okay. This is an issue with the initial cloning of the repo. The full command should be.
```bash
git clone git@github.com:logsdon-lab/CenMAP.git --recurse-submodules
```

Without that flag, it's missing `workflow/scripts/stv_fix/scripts/live_HORs_filter.py`, a file from a submodule. 

You should be able to fix this by running.
```bash
make update_submodules
```

Let me know if that works,
Keith

**Comment by chunlinxiao** [comment]
I remembered there was a problem when using "--recurse-submodules", thus I cloned without it.

Now following your "make update_submodules",  still have issue as below:


Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:koisland/stv.git' into submodule path 'CenMAP/workflow/scripts/stv_fix' failed
Failed to clone 'workflow/scripts/stv_fix' a second time, aborting
make: *** [Makefile:15: update_submodules] Error 1

**Comment by chunlinxiao** [comment]
after "run git pull && make submodules command"  - I got:

 * [new tag]         v0.1.4             -> v0.1.4
Updating 0eaf328..01bc4a6
Fast-forward
 .gitmodules | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
make: *** No rule to make target 'submodules'.  Stop.

**Comment by koisland** [comment]
Sorry, my bad. The command is `make update_submodules`.

**Comment by chunlinxiao** [comment]
still error:

CenMAP>git pull && make update_submodules

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:koisland/stv.git' into submodule path '/net/intdev/varpipe01/varpipe/chunlin/CenMAP/workflow/scripts/stv_fix' failed
Failed to clone 'workflow/scripts/stv_fix' a second time, aborting
make: *** [Makefile:15: update_submodules] Error 1

**Comment by koisland** [comment]
Hi @chunlinxiao,

It looks like the submodule URL wasn't updated. Try `git submodule sync && make update_submodules`. This will update git's pointer to the new URL in your local repo and then update it. Hopefully, that should work.

Thanks,
Keith

**Comment by koisland** [comment]
Awesome! Thanks for bearing with the debugging.

**Comment by chunlinxiao** [comment]
**the testing process seemed hanging here:**

Activating conda environment: .snakemake/conda/d929071de8a7c5c417717672309902e4_
Touching output file results/humas_hmmer/split_cens_for_humas_hmmer_chr16.done.
[Fri Sep 20 11:49:39 2024]
Finished job 350.
8 of 285 steps (3%) done
MissingInputException in rule aggregate_format_all_stv_row in file CenMAP/workflow/rules/plot_hor_stv.smk, line 80:
Missing input files for rule aggregate_format_all_stv_row:
    output: results/hor_stv/bed/chr16_AS-HOR_stv_row.all.bed
    wildcards: chr=chr16
    affected files:
        results/hor_stv/bed/chr16/HG002_chr16_chr16_MATERNAL:35413923-38574407_stv_row.bed
        results/hor_stv/bed/chr16/AS-HOR_HG002_chr16_chr16_PATERNAL:34212836-37771735_stv_row.bed
        results/hor_stv/bed/chr16/HG002_chr16_chr16_PATERNAL:34212836-37771735_stv_row.bed
        results/hor_stv/bed/chr16/AS-HOR_HG002_chr16_chr16_MATERNAL:35413923-38574407_stv_row.bed

**I thus stopped it.  But when I re-run it, I got the following error:**

RuntimeError: can't create new thread at interpreter shutdown
Exception in thread Thread-32:
Traceback (most recent call last):
  File "miniconda3/envs/cenmap/lib/python3.12/threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "miniconda3/envs/cenmap/lib/python3.12/site-packages/snakemake/benchmark.py", line 242, in run
    self.function(*self.args, **self.kwargs)
  File "miniconda3/envs/cenmap/lib/python3.12/site-packages/snakemake/benchmark.py", line 278, in _action
    self._timer.start()
  File "miniconda3/envs/cenmap/lib/python3.12/threading.py", line 971, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown

**Comment by koisland** [comment]
Hi @chunlinxiao,

I haven't encountered this error before so I'll need to run CenMAP on HG002 and see if I can reproduce it. I'll get back to you on this.

Thanks,
Keith

**Comment by koisland** [comment]
This is helpful. This is an issue with Snakemake checkpoints. I'm looking into this.

I'm not sure about the second issue.

**Comment by chunlinxiao** [comment]
thanks @koisland - followed your suggestion and it run smoothly until now (message below):

[Mon Sep 30 20:14:09 2024]
Finished job 325.
96 of 295 steps (33%) done
MissingInputException in rule aggregate_format_all_stv_row in file CenMAP/workflow/rules/plot_hor_stv.smk, line 85:
Missing input files for rule aggregate_format_all_stv_row:
    output: results/hor_stv/bed/chr8_AS-HOR_stv_row.all.bed
    wildcards: chr=chr8
    affected files:
        results/hor_stv/bed/chr8/HG002_chr8_chr8_MATERNAL:43008335-47438217_stv_row.bed
        results/hor_stv/bed/chr8/AS-HOR_HG002_chr8_chr8_MATERNAL:43008335-47438217_stv_row.bed

 No other error messages!

**Comment by koisland** [comment]
Hmm... I'm not sure why you're still getting this error. Can you post your config file and the output of `git log`?

**Comment by chunlinxiao** [comment]
@koisland thanks very much for looking into this.


File1: [git_log.log](https://github.com/user-attachments/files/17263042/git_log.log)
File2: [config_hg002_for_koisland.yaml.txt](https://github.com/user-attachments/files/17263079/config_hg002_for_koisland.yaml.txt)

File2 renamed as "txt" for uploading purpose, and its Line32, Line38, Line69 with "~" replacing our internal path (no other changes).

**Comment by koisland** [comment]
Closing. These issues have been fixed in more recent versions of CenMap. If not, you can reopen this issue or open a new one.
